//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class web_dataEntities : DbContext
    {
        public web_dataEntities()
            : base("name=web_dataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<author> authors { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<news_detail> news_detail { get; set; }
        public virtual DbSet<web_name> web_name { get; set; }
        public virtual DbSet<similarity> similarities { get; set; }
    }
}
