//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class news_detail
    {
        public int news_id { get; set; }
        public string date { get; set; }
        public string heading { get; set; }
        public string content { get; set; }
        public Nullable<int> id_authors { get; set; }
        public Nullable<int> id_categories { get; set; }
        public Nullable<int> id_web { get; set; }
    }
}
