//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class similarity
    {
        public int similarityID { get; set; }
        public Nullable<int> scrapednewsID { get; set; }
        public Nullable<int> othersnewsID { get; set; }
        public Nullable<double> score { get; set; }
    }
}
